create type "public"."EmployeeStatus" as enum ('active', 'terminated', 'suspended', 'onLeave', 'onDuty');

create type "public"."TicketStatus" as enum ('unpaid', 'paid', 'cancelled', 'transferred', 'overdue');

create table "public"."_role_permissions" (
    "role_id" bigint not null,
    "permission_id" bigint not null
);


create table "public"."_ticket_violations" (
    "ticket_id" bigint not null,
    "violation_id" bigint not null
);


create table "public"."employees" (
    "id" bigint generated by default as identity not null,
    "first_name" character varying not null,
    "middle_name" character varying default ''::character varying,
    "last_name" character varying not null,
    "suffix" character varying default ''::character varying,
    "status" "EmployeeStatus" not null default 'active'::"EmployeeStatus",
    "birthdate" date not null,
    "employee_no" character varying,
    "role" json not null,
    "user_id" uuid not null,
    "created_by" uuid not null default auth.uid(),
    "updated_by" uuid not null default auth.uid(),
    "deleted_by" uuid,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "deleted_at" timestamp without time zone
);


create table "public"."impounds" (
    "id" bigint generated by default as identity not null,
    "ticket_id" bigint not null,
    "site" character varying not null,
    "impounted_at" timestamp without time zone not null,
    "released_by" uuid,
    "released_at" timestamp without time zone
);


create table "public"."permissions" (
    "id" bigint generated by default as identity not null,
    "permission" character varying not null
);


create table "public"."roles" (
    "id" bigint generated by default as identity not null,
    "role" character varying not null
);


create table "public"."ticket_issue_location" (
    "id" bigint generated by default as identity not null,
    "ticket_id" bigint not null,
    "address" character varying not null,
    "latitude" double precision not null,
    "longitude" double precision not null
);


create table "public"."ticket_numbers_auto" (
    "ticket_number" bigint generated by default as identity not null,
    "ticket_id" bigint not null
);


create table "public"."ticket_numbers_manual" (
    "ticket_number" bigint not null,
    "ticket_id" bigint not null
);


create table "public"."ticket_payment" (
    "id" bigint generated by default as identity not null,
    "ticket_id" bigint not null,
    "or_number" character varying not null,
    "discounted" boolean not null default false,
    "discount_amount" real not null default '0'::real,
    "paid_amount" real not null default '0'::real,
    "cashier" uuid not null default auth.uid(),
    "paid_at" timestamp without time zone not null default now(),
    "updated_by" uuid not null default auth.uid(),
    "udpated_at" timestamp without time zone not null default now()
);


create table "public"."tickets" (
    "id" bigint generated by default as identity not null,
    "first_name" character varying not null,
    "middle_name" character varying default ''::character varying,
    "last_name" character varying not null,
    "suffix" character varying default ''::character varying,
    "birthdate" date,
    "status" "TicketStatus" not null default 'unpaid'::"TicketStatus",
    "violation_date" date not null,
    "violation_time" time without time zone not null,
    "vehicle_type_id" bigint not null,
    "enforcer_id" uuid not null,
    "created_by" uuid not null default auth.uid(),
    "udpated_by" uuid not null default auth.uid(),
    "deleted_by" uuid,
    "created_at" timestamp without time zone not null default now(),
    "updated_at" timestamp without time zone not null default now(),
    "deleted_at" timestamp without time zone
);


create table "public"."traffic_posts" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null,
    "address" character varying not null,
    "latitude" double precision not null,
    "longitude" double precision not null,
    "enabled" boolean not null default true,
    "created_by" uuid not null default auth.uid(),
    "updated_by" uuid not null default auth.uid(),
    "deleted_by" uuid,
    "created_at " timestamp without time zone not null default now(),
    "updated_at" timestamp without time zone not null default now(),
    "deleted_at" timestamp without time zone
);


create table "public"."vehicle_types" (
    "id" bigint generated by default as identity not null,
    "type" character varying not null,
    "big_vehicle" boolean not null default false,
    "hidden" boolean not null default false,
    "created_by" uuid not null default auth.uid(),
    "updated_by" uuid not null default auth.uid(),
    "deleted_by" uuid,
    "created_at" timestamp without time zone not null default now(),
    "updated_at" timestamp without time zone not null default now(),
    "deleted_at" timestamp without time zone
);


create table "public"."violations" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null,
    "fine" json not null,
    "enabled" boolean not null default true,
    "created_by" uuid not null default auth.uid(),
    "updated_by" uuid not null default auth.uid(),
    "deleted_by" uuid,
    "created_at" timestamp without time zone not null default now(),
    "updated_at" timestamp without time zone not null default now(),
    "deleted_at" timestamp without time zone
);


CREATE UNIQUE INDEX "Employees_employee_no_key" ON public.employees USING btree (employee_no);

CREATE UNIQUE INDEX "Employees_id_key" ON public.employees USING btree (id);

CREATE UNIQUE INDEX "Employees_pkey" ON public.employees USING btree (id);

CREATE UNIQUE INDEX "Tickets_pkey" ON public.tickets USING btree (id);

CREATE UNIQUE INDEX _role_permissions_pkey ON public._role_permissions USING btree (role_id, permission_id);

CREATE UNIQUE INDEX _ticket_violations_pkey ON public._ticket_violations USING btree (ticket_id, violation_id);

CREATE UNIQUE INDEX impounds_pkey ON public.impounds USING btree (id);

CREATE UNIQUE INDEX permissions_pkey ON public.permissions USING btree (id);

CREATE UNIQUE INDEX roles_pkey ON public.roles USING btree (id);

CREATE UNIQUE INDEX ticket_issue_location_pkey ON public.ticket_issue_location USING btree (id);

CREATE UNIQUE INDEX ticket_numbers_auto_pkey ON public.ticket_numbers_auto USING btree (ticket_id);

CREATE UNIQUE INDEX ticket_numbers_manual_pkey ON public.ticket_numbers_manual USING btree (ticket_id);

CREATE UNIQUE INDEX ticket_numbers_manual_ticket_id_key ON public.ticket_numbers_manual USING btree (ticket_id);

CREATE UNIQUE INDEX ticket_numbers_manual_ticket_number_key ON public.ticket_numbers_manual USING btree (ticket_number);

CREATE UNIQUE INDEX ticket_payment_or_number_key ON public.ticket_payment USING btree (or_number);

CREATE UNIQUE INDEX ticket_payment_pkey ON public.ticket_payment USING btree (id);

CREATE UNIQUE INDEX traffic_posts_pkey ON public.traffic_posts USING btree (id);

CREATE UNIQUE INDEX vehicle_types_pkey ON public.vehicle_types USING btree (id);

CREATE UNIQUE INDEX violations_pkey ON public.violations USING btree (id);

alter table "public"."_role_permissions" add constraint "_role_permissions_pkey" PRIMARY KEY using index "_role_permissions_pkey";

alter table "public"."_ticket_violations" add constraint "_ticket_violations_pkey" PRIMARY KEY using index "_ticket_violations_pkey";

alter table "public"."employees" add constraint "Employees_pkey" PRIMARY KEY using index "Employees_pkey";

alter table "public"."impounds" add constraint "impounds_pkey" PRIMARY KEY using index "impounds_pkey";

alter table "public"."permissions" add constraint "permissions_pkey" PRIMARY KEY using index "permissions_pkey";

alter table "public"."roles" add constraint "roles_pkey" PRIMARY KEY using index "roles_pkey";

alter table "public"."ticket_issue_location" add constraint "ticket_issue_location_pkey" PRIMARY KEY using index "ticket_issue_location_pkey";

alter table "public"."ticket_numbers_auto" add constraint "ticket_numbers_auto_pkey" PRIMARY KEY using index "ticket_numbers_auto_pkey";

alter table "public"."ticket_numbers_manual" add constraint "ticket_numbers_manual_pkey" PRIMARY KEY using index "ticket_numbers_manual_pkey";

alter table "public"."ticket_payment" add constraint "ticket_payment_pkey" PRIMARY KEY using index "ticket_payment_pkey";

alter table "public"."tickets" add constraint "Tickets_pkey" PRIMARY KEY using index "Tickets_pkey";

alter table "public"."traffic_posts" add constraint "traffic_posts_pkey" PRIMARY KEY using index "traffic_posts_pkey";

alter table "public"."vehicle_types" add constraint "vehicle_types_pkey" PRIMARY KEY using index "vehicle_types_pkey";

alter table "public"."violations" add constraint "violations_pkey" PRIMARY KEY using index "violations_pkey";

alter table "public"."_role_permissions" add constraint "public__role_permissions_permission_id_fkey" FOREIGN KEY (permission_id) REFERENCES permissions(id) not valid;

alter table "public"."_role_permissions" validate constraint "public__role_permissions_permission_id_fkey";

alter table "public"."_role_permissions" add constraint "public__role_permissions_role_id_fkey" FOREIGN KEY (role_id) REFERENCES roles(id) not valid;

alter table "public"."_role_permissions" validate constraint "public__role_permissions_role_id_fkey";

alter table "public"."_ticket_violations" add constraint "public__ticket_violations_ticket_id_fkey" FOREIGN KEY (ticket_id) REFERENCES tickets(id) not valid;

alter table "public"."_ticket_violations" validate constraint "public__ticket_violations_ticket_id_fkey";

alter table "public"."_ticket_violations" add constraint "public__ticket_violations_violation_id_fkey" FOREIGN KEY (violation_id) REFERENCES violations(id) not valid;

alter table "public"."_ticket_violations" validate constraint "public__ticket_violations_violation_id_fkey";

alter table "public"."employees" add constraint "Employees_employee_no_key" UNIQUE using index "Employees_employee_no_key";

alter table "public"."employees" add constraint "Employees_id_key" UNIQUE using index "Employees_id_key";

alter table "public"."employees" add constraint "public_Employees_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) not valid;

alter table "public"."employees" validate constraint "public_Employees_created_by_fkey";

alter table "public"."employees" add constraint "public_Employees_deleted_by_fkey" FOREIGN KEY (deleted_by) REFERENCES auth.users(id) not valid;

alter table "public"."employees" validate constraint "public_Employees_deleted_by_fkey";

alter table "public"."employees" add constraint "public_Employees_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES auth.users(id) not valid;

alter table "public"."employees" validate constraint "public_Employees_updated_by_fkey";

alter table "public"."employees" add constraint "public_Employees_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."employees" validate constraint "public_Employees_user_id_fkey";

alter table "public"."impounds" add constraint "public_impounds_released_by_fkey" FOREIGN KEY (released_by) REFERENCES auth.users(id) not valid;

alter table "public"."impounds" validate constraint "public_impounds_released_by_fkey";

alter table "public"."impounds" add constraint "public_impounds_ticket_id_fkey" FOREIGN KEY (ticket_id) REFERENCES tickets(id) not valid;

alter table "public"."impounds" validate constraint "public_impounds_ticket_id_fkey";

alter table "public"."ticket_issue_location" add constraint "public_ticket_issue_location_ticket_id_fkey" FOREIGN KEY (ticket_id) REFERENCES tickets(id) not valid;

alter table "public"."ticket_issue_location" validate constraint "public_ticket_issue_location_ticket_id_fkey";

alter table "public"."ticket_numbers_auto" add constraint "public_ticket_numbers_auto_ticket_id_fkey" FOREIGN KEY (ticket_id) REFERENCES tickets(id) not valid;

alter table "public"."ticket_numbers_auto" validate constraint "public_ticket_numbers_auto_ticket_id_fkey";

alter table "public"."ticket_numbers_manual" add constraint "public_ticket_numbers_manual_ticket_id_fkey" FOREIGN KEY (ticket_id) REFERENCES tickets(id) not valid;

alter table "public"."ticket_numbers_manual" validate constraint "public_ticket_numbers_manual_ticket_id_fkey";

alter table "public"."ticket_numbers_manual" add constraint "ticket_numbers_manual_ticket_id_key" UNIQUE using index "ticket_numbers_manual_ticket_id_key";

alter table "public"."ticket_numbers_manual" add constraint "ticket_numbers_manual_ticket_number_key" UNIQUE using index "ticket_numbers_manual_ticket_number_key";

alter table "public"."ticket_payment" add constraint "public_ticket_payment_cashier_fkey" FOREIGN KEY (cashier) REFERENCES auth.users(id) not valid;

alter table "public"."ticket_payment" validate constraint "public_ticket_payment_cashier_fkey";

alter table "public"."ticket_payment" add constraint "public_ticket_payment_ticket_id_fkey" FOREIGN KEY (ticket_id) REFERENCES tickets(id) not valid;

alter table "public"."ticket_payment" validate constraint "public_ticket_payment_ticket_id_fkey";

alter table "public"."ticket_payment" add constraint "public_ticket_payment_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES auth.users(id) not valid;

alter table "public"."ticket_payment" validate constraint "public_ticket_payment_updated_by_fkey";

alter table "public"."ticket_payment" add constraint "ticket_payment_or_number_key" UNIQUE using index "ticket_payment_or_number_key";

alter table "public"."tickets" add constraint "public_Tickets_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) not valid;

alter table "public"."tickets" validate constraint "public_Tickets_created_by_fkey";

alter table "public"."tickets" add constraint "public_Tickets_deleted_by_fkey" FOREIGN KEY (deleted_by) REFERENCES auth.users(id) not valid;

alter table "public"."tickets" validate constraint "public_Tickets_deleted_by_fkey";

alter table "public"."tickets" add constraint "public_Tickets_enforcer_id_fkey" FOREIGN KEY (enforcer_id) REFERENCES auth.users(id) not valid;

alter table "public"."tickets" validate constraint "public_Tickets_enforcer_id_fkey";

alter table "public"."tickets" add constraint "public_Tickets_udpated_by_fkey" FOREIGN KEY (udpated_by) REFERENCES auth.users(id) not valid;

alter table "public"."tickets" validate constraint "public_Tickets_udpated_by_fkey";

alter table "public"."traffic_posts" add constraint "public_traffic_posts_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) not valid;

alter table "public"."traffic_posts" validate constraint "public_traffic_posts_created_by_fkey";

alter table "public"."traffic_posts" add constraint "public_traffic_posts_deleted_by_fkey" FOREIGN KEY (deleted_by) REFERENCES auth.users(id) not valid;

alter table "public"."traffic_posts" validate constraint "public_traffic_posts_deleted_by_fkey";

alter table "public"."traffic_posts" add constraint "public_traffic_posts_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES auth.users(id) not valid;

alter table "public"."traffic_posts" validate constraint "public_traffic_posts_updated_by_fkey";

alter table "public"."vehicle_types" add constraint "public_vehicle_types_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) not valid;

alter table "public"."vehicle_types" validate constraint "public_vehicle_types_created_by_fkey";

alter table "public"."vehicle_types" add constraint "public_vehicle_types_deleted_by_fkey" FOREIGN KEY (deleted_by) REFERENCES auth.users(id) not valid;

alter table "public"."vehicle_types" validate constraint "public_vehicle_types_deleted_by_fkey";

alter table "public"."vehicle_types" add constraint "public_vehicle_types_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES auth.users(id) not valid;

alter table "public"."vehicle_types" validate constraint "public_vehicle_types_updated_by_fkey";

alter table "public"."violations" add constraint "public_violations_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) not valid;

alter table "public"."violations" validate constraint "public_violations_created_by_fkey";

alter table "public"."violations" add constraint "public_violations_deleted_by_fkey" FOREIGN KEY (deleted_by) REFERENCES auth.users(id) not valid;

alter table "public"."violations" validate constraint "public_violations_deleted_by_fkey";

alter table "public"."violations" add constraint "public_violations_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES auth.users(id) not valid;

alter table "public"."violations" validate constraint "public_violations_updated_by_fkey";

grant delete on table "public"."_role_permissions" to "anon";

grant insert on table "public"."_role_permissions" to "anon";

grant references on table "public"."_role_permissions" to "anon";

grant select on table "public"."_role_permissions" to "anon";

grant trigger on table "public"."_role_permissions" to "anon";

grant truncate on table "public"."_role_permissions" to "anon";

grant update on table "public"."_role_permissions" to "anon";

grant delete on table "public"."_role_permissions" to "authenticated";

grant insert on table "public"."_role_permissions" to "authenticated";

grant references on table "public"."_role_permissions" to "authenticated";

grant select on table "public"."_role_permissions" to "authenticated";

grant trigger on table "public"."_role_permissions" to "authenticated";

grant truncate on table "public"."_role_permissions" to "authenticated";

grant update on table "public"."_role_permissions" to "authenticated";

grant delete on table "public"."_role_permissions" to "service_role";

grant insert on table "public"."_role_permissions" to "service_role";

grant references on table "public"."_role_permissions" to "service_role";

grant select on table "public"."_role_permissions" to "service_role";

grant trigger on table "public"."_role_permissions" to "service_role";

grant truncate on table "public"."_role_permissions" to "service_role";

grant update on table "public"."_role_permissions" to "service_role";

grant delete on table "public"."_ticket_violations" to "anon";

grant insert on table "public"."_ticket_violations" to "anon";

grant references on table "public"."_ticket_violations" to "anon";

grant select on table "public"."_ticket_violations" to "anon";

grant trigger on table "public"."_ticket_violations" to "anon";

grant truncate on table "public"."_ticket_violations" to "anon";

grant update on table "public"."_ticket_violations" to "anon";

grant delete on table "public"."_ticket_violations" to "authenticated";

grant insert on table "public"."_ticket_violations" to "authenticated";

grant references on table "public"."_ticket_violations" to "authenticated";

grant select on table "public"."_ticket_violations" to "authenticated";

grant trigger on table "public"."_ticket_violations" to "authenticated";

grant truncate on table "public"."_ticket_violations" to "authenticated";

grant update on table "public"."_ticket_violations" to "authenticated";

grant delete on table "public"."_ticket_violations" to "service_role";

grant insert on table "public"."_ticket_violations" to "service_role";

grant references on table "public"."_ticket_violations" to "service_role";

grant select on table "public"."_ticket_violations" to "service_role";

grant trigger on table "public"."_ticket_violations" to "service_role";

grant truncate on table "public"."_ticket_violations" to "service_role";

grant update on table "public"."_ticket_violations" to "service_role";

grant delete on table "public"."employees" to "anon";

grant insert on table "public"."employees" to "anon";

grant references on table "public"."employees" to "anon";

grant select on table "public"."employees" to "anon";

grant trigger on table "public"."employees" to "anon";

grant truncate on table "public"."employees" to "anon";

grant update on table "public"."employees" to "anon";

grant delete on table "public"."employees" to "authenticated";

grant insert on table "public"."employees" to "authenticated";

grant references on table "public"."employees" to "authenticated";

grant select on table "public"."employees" to "authenticated";

grant trigger on table "public"."employees" to "authenticated";

grant truncate on table "public"."employees" to "authenticated";

grant update on table "public"."employees" to "authenticated";

grant delete on table "public"."employees" to "service_role";

grant insert on table "public"."employees" to "service_role";

grant references on table "public"."employees" to "service_role";

grant select on table "public"."employees" to "service_role";

grant trigger on table "public"."employees" to "service_role";

grant truncate on table "public"."employees" to "service_role";

grant update on table "public"."employees" to "service_role";

grant delete on table "public"."impounds" to "anon";

grant insert on table "public"."impounds" to "anon";

grant references on table "public"."impounds" to "anon";

grant select on table "public"."impounds" to "anon";

grant trigger on table "public"."impounds" to "anon";

grant truncate on table "public"."impounds" to "anon";

grant update on table "public"."impounds" to "anon";

grant delete on table "public"."impounds" to "authenticated";

grant insert on table "public"."impounds" to "authenticated";

grant references on table "public"."impounds" to "authenticated";

grant select on table "public"."impounds" to "authenticated";

grant trigger on table "public"."impounds" to "authenticated";

grant truncate on table "public"."impounds" to "authenticated";

grant update on table "public"."impounds" to "authenticated";

grant delete on table "public"."impounds" to "service_role";

grant insert on table "public"."impounds" to "service_role";

grant references on table "public"."impounds" to "service_role";

grant select on table "public"."impounds" to "service_role";

grant trigger on table "public"."impounds" to "service_role";

grant truncate on table "public"."impounds" to "service_role";

grant update on table "public"."impounds" to "service_role";

grant delete on table "public"."permissions" to "anon";

grant insert on table "public"."permissions" to "anon";

grant references on table "public"."permissions" to "anon";

grant select on table "public"."permissions" to "anon";

grant trigger on table "public"."permissions" to "anon";

grant truncate on table "public"."permissions" to "anon";

grant update on table "public"."permissions" to "anon";

grant delete on table "public"."permissions" to "authenticated";

grant insert on table "public"."permissions" to "authenticated";

grant references on table "public"."permissions" to "authenticated";

grant select on table "public"."permissions" to "authenticated";

grant trigger on table "public"."permissions" to "authenticated";

grant truncate on table "public"."permissions" to "authenticated";

grant update on table "public"."permissions" to "authenticated";

grant delete on table "public"."permissions" to "service_role";

grant insert on table "public"."permissions" to "service_role";

grant references on table "public"."permissions" to "service_role";

grant select on table "public"."permissions" to "service_role";

grant trigger on table "public"."permissions" to "service_role";

grant truncate on table "public"."permissions" to "service_role";

grant update on table "public"."permissions" to "service_role";

grant delete on table "public"."roles" to "anon";

grant insert on table "public"."roles" to "anon";

grant references on table "public"."roles" to "anon";

grant select on table "public"."roles" to "anon";

grant trigger on table "public"."roles" to "anon";

grant truncate on table "public"."roles" to "anon";

grant update on table "public"."roles" to "anon";

grant delete on table "public"."roles" to "authenticated";

grant insert on table "public"."roles" to "authenticated";

grant references on table "public"."roles" to "authenticated";

grant select on table "public"."roles" to "authenticated";

grant trigger on table "public"."roles" to "authenticated";

grant truncate on table "public"."roles" to "authenticated";

grant update on table "public"."roles" to "authenticated";

grant delete on table "public"."roles" to "service_role";

grant insert on table "public"."roles" to "service_role";

grant references on table "public"."roles" to "service_role";

grant select on table "public"."roles" to "service_role";

grant trigger on table "public"."roles" to "service_role";

grant truncate on table "public"."roles" to "service_role";

grant update on table "public"."roles" to "service_role";

grant delete on table "public"."ticket_issue_location" to "anon";

grant insert on table "public"."ticket_issue_location" to "anon";

grant references on table "public"."ticket_issue_location" to "anon";

grant select on table "public"."ticket_issue_location" to "anon";

grant trigger on table "public"."ticket_issue_location" to "anon";

grant truncate on table "public"."ticket_issue_location" to "anon";

grant update on table "public"."ticket_issue_location" to "anon";

grant delete on table "public"."ticket_issue_location" to "authenticated";

grant insert on table "public"."ticket_issue_location" to "authenticated";

grant references on table "public"."ticket_issue_location" to "authenticated";

grant select on table "public"."ticket_issue_location" to "authenticated";

grant trigger on table "public"."ticket_issue_location" to "authenticated";

grant truncate on table "public"."ticket_issue_location" to "authenticated";

grant update on table "public"."ticket_issue_location" to "authenticated";

grant delete on table "public"."ticket_issue_location" to "service_role";

grant insert on table "public"."ticket_issue_location" to "service_role";

grant references on table "public"."ticket_issue_location" to "service_role";

grant select on table "public"."ticket_issue_location" to "service_role";

grant trigger on table "public"."ticket_issue_location" to "service_role";

grant truncate on table "public"."ticket_issue_location" to "service_role";

grant update on table "public"."ticket_issue_location" to "service_role";

grant delete on table "public"."ticket_numbers_auto" to "anon";

grant insert on table "public"."ticket_numbers_auto" to "anon";

grant references on table "public"."ticket_numbers_auto" to "anon";

grant select on table "public"."ticket_numbers_auto" to "anon";

grant trigger on table "public"."ticket_numbers_auto" to "anon";

grant truncate on table "public"."ticket_numbers_auto" to "anon";

grant update on table "public"."ticket_numbers_auto" to "anon";

grant delete on table "public"."ticket_numbers_auto" to "authenticated";

grant insert on table "public"."ticket_numbers_auto" to "authenticated";

grant references on table "public"."ticket_numbers_auto" to "authenticated";

grant select on table "public"."ticket_numbers_auto" to "authenticated";

grant trigger on table "public"."ticket_numbers_auto" to "authenticated";

grant truncate on table "public"."ticket_numbers_auto" to "authenticated";

grant update on table "public"."ticket_numbers_auto" to "authenticated";

grant delete on table "public"."ticket_numbers_auto" to "service_role";

grant insert on table "public"."ticket_numbers_auto" to "service_role";

grant references on table "public"."ticket_numbers_auto" to "service_role";

grant select on table "public"."ticket_numbers_auto" to "service_role";

grant trigger on table "public"."ticket_numbers_auto" to "service_role";

grant truncate on table "public"."ticket_numbers_auto" to "service_role";

grant update on table "public"."ticket_numbers_auto" to "service_role";

grant delete on table "public"."ticket_numbers_manual" to "anon";

grant insert on table "public"."ticket_numbers_manual" to "anon";

grant references on table "public"."ticket_numbers_manual" to "anon";

grant select on table "public"."ticket_numbers_manual" to "anon";

grant trigger on table "public"."ticket_numbers_manual" to "anon";

grant truncate on table "public"."ticket_numbers_manual" to "anon";

grant update on table "public"."ticket_numbers_manual" to "anon";

grant delete on table "public"."ticket_numbers_manual" to "authenticated";

grant insert on table "public"."ticket_numbers_manual" to "authenticated";

grant references on table "public"."ticket_numbers_manual" to "authenticated";

grant select on table "public"."ticket_numbers_manual" to "authenticated";

grant trigger on table "public"."ticket_numbers_manual" to "authenticated";

grant truncate on table "public"."ticket_numbers_manual" to "authenticated";

grant update on table "public"."ticket_numbers_manual" to "authenticated";

grant delete on table "public"."ticket_numbers_manual" to "service_role";

grant insert on table "public"."ticket_numbers_manual" to "service_role";

grant references on table "public"."ticket_numbers_manual" to "service_role";

grant select on table "public"."ticket_numbers_manual" to "service_role";

grant trigger on table "public"."ticket_numbers_manual" to "service_role";

grant truncate on table "public"."ticket_numbers_manual" to "service_role";

grant update on table "public"."ticket_numbers_manual" to "service_role";

grant delete on table "public"."ticket_payment" to "anon";

grant insert on table "public"."ticket_payment" to "anon";

grant references on table "public"."ticket_payment" to "anon";

grant select on table "public"."ticket_payment" to "anon";

grant trigger on table "public"."ticket_payment" to "anon";

grant truncate on table "public"."ticket_payment" to "anon";

grant update on table "public"."ticket_payment" to "anon";

grant delete on table "public"."ticket_payment" to "authenticated";

grant insert on table "public"."ticket_payment" to "authenticated";

grant references on table "public"."ticket_payment" to "authenticated";

grant select on table "public"."ticket_payment" to "authenticated";

grant trigger on table "public"."ticket_payment" to "authenticated";

grant truncate on table "public"."ticket_payment" to "authenticated";

grant update on table "public"."ticket_payment" to "authenticated";

grant delete on table "public"."ticket_payment" to "service_role";

grant insert on table "public"."ticket_payment" to "service_role";

grant references on table "public"."ticket_payment" to "service_role";

grant select on table "public"."ticket_payment" to "service_role";

grant trigger on table "public"."ticket_payment" to "service_role";

grant truncate on table "public"."ticket_payment" to "service_role";

grant update on table "public"."ticket_payment" to "service_role";

grant delete on table "public"."tickets" to "anon";

grant insert on table "public"."tickets" to "anon";

grant references on table "public"."tickets" to "anon";

grant select on table "public"."tickets" to "anon";

grant trigger on table "public"."tickets" to "anon";

grant truncate on table "public"."tickets" to "anon";

grant update on table "public"."tickets" to "anon";

grant delete on table "public"."tickets" to "authenticated";

grant insert on table "public"."tickets" to "authenticated";

grant references on table "public"."tickets" to "authenticated";

grant select on table "public"."tickets" to "authenticated";

grant trigger on table "public"."tickets" to "authenticated";

grant truncate on table "public"."tickets" to "authenticated";

grant update on table "public"."tickets" to "authenticated";

grant delete on table "public"."tickets" to "service_role";

grant insert on table "public"."tickets" to "service_role";

grant references on table "public"."tickets" to "service_role";

grant select on table "public"."tickets" to "service_role";

grant trigger on table "public"."tickets" to "service_role";

grant truncate on table "public"."tickets" to "service_role";

grant update on table "public"."tickets" to "service_role";

grant delete on table "public"."traffic_posts" to "anon";

grant insert on table "public"."traffic_posts" to "anon";

grant references on table "public"."traffic_posts" to "anon";

grant select on table "public"."traffic_posts" to "anon";

grant trigger on table "public"."traffic_posts" to "anon";

grant truncate on table "public"."traffic_posts" to "anon";

grant update on table "public"."traffic_posts" to "anon";

grant delete on table "public"."traffic_posts" to "authenticated";

grant insert on table "public"."traffic_posts" to "authenticated";

grant references on table "public"."traffic_posts" to "authenticated";

grant select on table "public"."traffic_posts" to "authenticated";

grant trigger on table "public"."traffic_posts" to "authenticated";

grant truncate on table "public"."traffic_posts" to "authenticated";

grant update on table "public"."traffic_posts" to "authenticated";

grant delete on table "public"."traffic_posts" to "service_role";

grant insert on table "public"."traffic_posts" to "service_role";

grant references on table "public"."traffic_posts" to "service_role";

grant select on table "public"."traffic_posts" to "service_role";

grant trigger on table "public"."traffic_posts" to "service_role";

grant truncate on table "public"."traffic_posts" to "service_role";

grant update on table "public"."traffic_posts" to "service_role";

grant delete on table "public"."vehicle_types" to "anon";

grant insert on table "public"."vehicle_types" to "anon";

grant references on table "public"."vehicle_types" to "anon";

grant select on table "public"."vehicle_types" to "anon";

grant trigger on table "public"."vehicle_types" to "anon";

grant truncate on table "public"."vehicle_types" to "anon";

grant update on table "public"."vehicle_types" to "anon";

grant delete on table "public"."vehicle_types" to "authenticated";

grant insert on table "public"."vehicle_types" to "authenticated";

grant references on table "public"."vehicle_types" to "authenticated";

grant select on table "public"."vehicle_types" to "authenticated";

grant trigger on table "public"."vehicle_types" to "authenticated";

grant truncate on table "public"."vehicle_types" to "authenticated";

grant update on table "public"."vehicle_types" to "authenticated";

grant delete on table "public"."vehicle_types" to "service_role";

grant insert on table "public"."vehicle_types" to "service_role";

grant references on table "public"."vehicle_types" to "service_role";

grant select on table "public"."vehicle_types" to "service_role";

grant trigger on table "public"."vehicle_types" to "service_role";

grant truncate on table "public"."vehicle_types" to "service_role";

grant update on table "public"."vehicle_types" to "service_role";

grant delete on table "public"."violations" to "anon";

grant insert on table "public"."violations" to "anon";

grant references on table "public"."violations" to "anon";

grant select on table "public"."violations" to "anon";

grant trigger on table "public"."violations" to "anon";

grant truncate on table "public"."violations" to "anon";

grant update on table "public"."violations" to "anon";

grant delete on table "public"."violations" to "authenticated";

grant insert on table "public"."violations" to "authenticated";

grant references on table "public"."violations" to "authenticated";

grant select on table "public"."violations" to "authenticated";

grant trigger on table "public"."violations" to "authenticated";

grant truncate on table "public"."violations" to "authenticated";

grant update on table "public"."violations" to "authenticated";

grant delete on table "public"."violations" to "service_role";

grant insert on table "public"."violations" to "service_role";

grant references on table "public"."violations" to "service_role";

grant select on table "public"."violations" to "service_role";

grant trigger on table "public"."violations" to "service_role";

grant truncate on table "public"."violations" to "service_role";

grant update on table "public"."violations" to "service_role";


